services:
  solr:
    image: solr:8.8.2
    ports:
      - "8983:8983"
    environment:
      - SOLR_OPTS=-XX:-UseLargePages
    networkds:
      - snet
    command:
      - solr-demo

networks:
  snet:
    enable_ipv6: false
